### PR TITLE
Add Persister interface.

### PR DESCRIPTION
**Pull request by stephenwithav**
This assumes other PRs will be merged.

I'll rework it tomorrow to start from master. :)

### CODE REVIEW

**Comment by vimukthi-git** [comment]
@stephenwithav Why is this interface needed? 

According to my design, persistence should be handled in the backends.

**Comment by stephenwithav** [comment]
@vimukthi-git the Persister interface is needed to simplify the implementation of storage backends.

It's in `architecture` because I need to access `Job.state`.  I could easily add a `State` getter func to job, then move `Persister` to `backend`.  Would that be preferred?

**Comment by vimukthi-git** [comment]
@stephenwithav there is already a `state` getter for `Job`, you can get it by calling `job.State()`. Also If your backend needs to know all the fields of the job, I don't mind you casting the Item to `Job`  and accessing fields. I don't think a new Persister interface is required in any case.

**Comment by stephenwithav** [comment]
Thanks for pointing out the existing getter, @vimukthi-git -- I was too focused to see it.

I think you'll change your mind on the new interface once you see it in action.  I know I could implement persistence using `PriorityQueue`, but `Persister` offers a cleaner solution.

**Comment by stephenwithav** [comment]
Placing `Persister` in `backend` causes an import cycle.

I'm going to move it back to `architecture`, but I won't push until I finish the Postgres implementation of `Persister`.  I do think you'll like it once you can see the whole picture.

**Comment by vimukthi-git** [comment]
I sure hope this is a good idea. But my concern is I don't want to have multiple interfaces for implementers of backends to follow. 

If you can give me a rough design sketch of how you are going to implement the postgres backend that would help for me to understand your thinking. This will help to save time as well.

Assuming your idea is to isolate storage operations from the actual priority queue operations, I already thought about that before but it doesn't make sense to me as it restricts the ability to optimise operations for the backend implementer. But if you can show that this is the right approach I'm willing to consider.

**Comment by stephenwithav** [comment]
The idea is slightly different than what you're suggesting.  The scenario I'm envisioning:

`beanstalkg` is running with a single replica in a Kubernetes cluster that has several consumers.  If the replica fails, `beanstalkg` will be restarted on a new machine and lose all of the jobs it was storing.

`Persister` provides the solution.  If a `Persister` is set, anytime a job is placed in a tube (`Tube.Put`), the initial job and the tube it belongs to is persisted with `Persister.Put`.  When the job is completed (`Tube.Delete`), `Persister.Delete` would change the persisted state to 'DONE'.

When the single `beanstalkg` replica is restarted, it can reload all non-completed jobs into `PriorityQueue` and start serving again.

I think this is a better solution than implementing persistence with `PriorityQueue` because it reduces the number of trips to the database, so it improves performance.

If you care about performance and persistence is implemented solely with `PriorityQueue`, you would have to:

1.  embed `MinHeap` into a new struct, say Postges.
2.  Call `MinHeap.Enqueue`, `MinHeap.Delete` inside the corresponding Postgres funcs.
3.  Reimplement `operation.NewTubeHandler` to use new `PriorityQueCreator`s.

`Persister` just seems simpler to me.

**Comment by vimukthi-git** [comment]
@stephenwithav I agree with you in concept that we have to support this sort of recovery. Its part of high availability architecture for beanstalkg. But the problem is if you have this kind of postgres backend and also have in memory `state` in a `PriorityQueue` it creates inconsistency issues when there are more than one beanstalkg servers running using the same database because job states won't be tracked properly in the db at least according to current `Persister`interface. Notice that having multiple beanstalkg servers running against it is the reason I would want a database backend in the first place. Otherwise we could just implement a `binlog` as beanstalkd does and have a beanstalkg server run against it(Which also is part of the [roadmap](https://github.com/vimukthi-git/beanstalkg/milestones?direction=asc&sort=due_date&state=open)) before implementing HA. If you want to avoid inconsistency issues you will probably end up making the same number of database calls. Therefore implementing the entire `PriorityQueue` interface in Postgres or a Redis backend is the right abstraction level for me, where it allows the implementer the freedom to do perf optimisations taking into account HA. But I appreciate your thinking in this direction.

Also something related, I did a presentation covering the Beanstalkg architecture and roadmap here in Munich golang user group yesterday. These are the [slides](https://www.slideshare.net/VimukthiWickramasing/beanstalkg-76573237), please check and let me know your ideas.

**Comment by stephenwithav** [comment]
@vimukthi-git Very true on the inconsistencies if multiple `beanstalkg` servers exist.

One of my main concerns with wrapping all of the persistence logic with `PriorityQueue` is that while `PriorityQueue`s have no idea which `Tube` they belong to, so that information can't be persisted.  And if the tube name isn't persisted, `beanstalkg` can't properly recover from a crash--it'll know the jobs, but not the tubes to place them in.

I skimmed through your presentation and loved it!  The state transition diagrams were especially helpful.

**Comment by vimukthi-git** [comment]
@stephenwithav I thought of the tube name issue before, wanted to add a parameter to pass the tube name to `Init` function in `PriorityQueue` interface. You can do the refactoring now if you don't mind.

**Comment by stephenwithav** [comment]
It shall be done today!  Should we pass in a pointer to `Tube` or simply the tube name?

**Comment by vimukthi-git** [comment]
name should be enough as we don't want the backend to mess with tube it self. But feel free to pass in any additional generic information that would be required.

**Pull request closed without merging**
